/**
 * AUTO-GENERATED by scripts/sync-dyno-intel-human-praise.mjs — do not edit by hand.
 * Sources:
 * - src/i18n/locales/zh-Hant/common/dynoIntel.json
 * - src/i18n/locales/en/common/dynoIntel.json
 */
export const DYNO_INTEL_PR_PERCENTILE_FALLBACK_ZH = "【全人類官方 PR 值對照資料正在熱烈搜集中】\n\n當資料足夠，會在更新後解鎖；誠摯邀請你幫忙介紹新玩家，一同加速解鎖這座全球肉體極限座標！";

export const DYNO_INTEL_PR_PERCENTILE_FALLBACK_EN = "【Global Peer PR Percentile Data Is Actively Being Gathered】\nWhen sufficient data is accumulated, this feature will unlock via a backend sync. We sincerely invite you to recruit new players to accelerate the calibration of this ultimate coordinate of human physical limits!";

export const DYNO_INTEL_HALL_OF_FAME_SENTENCE_ZH = "在名人堂聖殿中，你正與 {{names}} 站在同一個王座座標。";

export const DYNO_INTEL_HALL_OF_FAME_SENTENCE_EN = "In the Hall of Fame sanctum, you share the same throne coordinate as {{names}}.";

export const DYNO_INTEL_HALL_OF_FAME_LEGAL_SHIELD_ZH = "本系統所收錄之各界名將、藝人運動表現數據，均為其生涯巔峰狀態，源自全球網路公開史料與賽事紀實。部分未公開之空白維度，均由 Dyno Intel 運動科學研究中心依據跨領域生理常模、肌纖維募集比例與物理特質進行高精度推算。本矩陣非臨床與官方賽事認證，數據並非 100% 絕對精準，僅供天梯對帳與娛樂參考。";

export const DYNO_INTEL_HALL_OF_FAME_LEGAL_SHIELD_EN = "All athletic performance metrics of world-class athletes and celebrities stored in this matrix represent their career-peak states, compiled from verified global public archives and official event chronicles. Any unpublished or missing dimensions are calculated via high-precision predictive models by the Dyno Intel Sports Science Research Center, based on cross-disciplinary physiological norms, muscle fiber recruitment ratios, and biomechanical traits. This matrix is not a clinical or sanctioned sporting certification. Data is not 100% absolute and is provided solely for leaderboard simulation, cross-era benchmarking, and entertainment purposes.";

export const DYNO_INTEL_HALL_OF_FAME_BLOCKED_REPLY_ZH = "在 Dyno Intel 的萬神殿深處，該分數帶已正式跨入凡人頂尖的神格區間。你目前的綜合實力尚未解鎖該重力場。拼盡全力訓練吧！當你將功能推向臨界點時，天梯大腦會在你的專屬報告中，為你開啟與該階層歷史傳奇的正面對帳通道！";

export const DYNO_INTEL_HALL_OF_FAME_BLOCKED_REPLY_EN = "In the deepest sanctum of the Dyno Intel Pantheon, this tier has officially crossed into the echelon of elite genetic outliers and peak human godhood. Your current aggregate physical capacity has not yet unlocked this gravitational field. Train harder, leave everything on the gym floor, and return with new numbers. When you push your metrics to the absolute threshold, the Core Mind will unlock the gateway for a direct, cross-era benchmarking session with the legends of this tier in your exclusive briefing.";

export const DYNO_INTEL_HALL_OF_FAME_GUIDED_REPLY_ZH = "你想探索哪一軸線的萬神殿？你可以試著問我：『爆發力 120 分還有誰？』或『心肺 130 分有哪些強者？』";

export const DYNO_INTEL_HALL_OF_FAME_GUIDED_REPLY_EN = "Which axis of the Pantheon do you want to explore? Try asking: \"Who else is at 120 explosive power?\" or \"Which legends sit at 130 cardio?\"";

export const DYNO_INTEL_HUMAN_PRAISE_BY_DECADE = {
  "0": {
    "populationClass": "嬰兒期",
    "overall": "在身體鍛鍊的世界裡，你目前處於嬰兒期；雖然聽起來很弱小，但意味著你有巨大的成長空間。建議找經驗豐富的訓練夥伴協助你，確保一切安全無虞；開始系統化鍛鍊後，你將會感受到飛速地進步，快速長大吧！",
    "neuro": "在嬰兒期，進步通常來得很快——只要掌握神經募集的方法，將訓練動作多加熟練，馬上就能往上晉升。你不是沒有力氣，只是還沒學會如何發力。衷心建議找個有經驗的訓練夥伴或專業教練引導，你的評分就能迅速提升。",
    "volume": "身體是過去生活習慣的累積，現在這個得分，就是過往生活型態的呈現。只要你願意做出稍微的改變，分數就會飛也似地成長，馬上突破 40 分、進入探索期。找個有經驗的夥伴建立初步訓練與飲食架構，你會變得更有力氣、更健康。"
  },
  "40": {
    "populationClass": "探索期",
    "overall": "你正處於探索期：好好認識自己的身體，認真熟練訓練動作，開始注重飲食搭配，並探索訓練與飲食如何影響身體。只要搭配得當，往 50 分、進入新手期是必然的。這趟旅程才剛剛開始，充滿熱情地探索吧！",
    "neuro": "探索期是大多數人的起始之地——你只是開始得比較晚，不會永遠停在這裡。大量學習與實作是必要的；找個有經驗的訓練夥伴協助建構初步動作架構，既能安全快速進步，又能有效避免傷病。",
    "volume": "你也知道自己剛剛開始，所以不要太在意這個階段的分數，訓練成果需要時間沉澱。建立新的飲食習慣與時間分配，注重營養並投入訓練。這場計劃不是衝刺短跑，而是馬拉松；持之以恆，50 分絕對可以達成。"
  },
  "50": {
    "populationClass": "新手期",
    "overall": "評分來到 50 以上，你已進入新手期，位於健康常模的入門線上。雖然跟更高階玩家比起來會覺得自己還在新手村，但目前的運動表現套用在日常生活裡已經很足夠。方式正確的話，努力與回報高度成正比，進步到 60 分、站上大眾健康常模指日可待！",
    "neuro": "新手期是最多健身愛好者的所在地——你已漸漸站穩腳步。不要覺得這個分數沒有什麼了不起：你已經比多數菜鳥有力氣，對重量掌控與技術動作也有一定純熟度。持之以恆，往上還有許多空間可以進步。",
    "volume": "現在看不出身材有明顯改變非常正常——萬丈高樓平地起，你才剛打好地基。這個階段最容易讓人放棄，因為改變好像有點卻又不明顯；堅定信念，一定能進步到 60 分以上，千萬不要在此停下腳步。"
  },
  "60": {
    "populationClass": "大眾健康常模",
    "overall": "你已站上大眾健康常模：在運動愛好者之中已是有規律投入的一群。大多數沒訓練、訓練頻率不夠的玩家拿不到這個評分，這證明投入有所回報。想進步到 70 分、成為進階健身者，需要時間累積與沉穩努力——對一般基因來說，那是富含挑戰性的目標。",
    "neuro": "走到大眾健康常模，各項表現已明顯跟新手拉開差距。沒有訓練或偶爾訓練的玩家，除非基因特別優秀，不然很難穩定拿到 60 分以上。你已開始規律訓練、注意飲食，也漸漸發現自己越變越強——付出努力就會獲得回報。70 分並非遙不可及。",
    "volume": "看著漸漸隆起的肌肉或漸漸消瘦的腰圍，成就感會在心底偷偷說你真的不錯。也許別人不一定察覺，但你一定有察覺身體在改變。投入的心力會顯著轉換為成果，期待你繼續往 70 分、進階健身者邁進。"
  },
  "70": {
    "populationClass": "進階健身者",
    "overall": "這個評分屬於進階健身者——規律訓練、飲食控制、避免傷病，才能走到這一步，必須給你比個讚。你在商業健身房裡高機率是優秀玩家之一，訓練痕跡也容易被察覺。目前的運動表現在專項運動中已相當有競爭力。要再往上成為高階玩家，時間成本與技術精進都會顯著提升——準備好了嗎？",
    "neuro": "獲得這個分數時，你的運動表現已屬於進階健身者序列。絕大多數人都要悉心鍛鍊才能站穩 70 分以上。特別注意：這個階段許多人因進步明顯而急於求成，傷病容易找上門。穩紮穩打，方能持續進步；配合熟練專項技術，你已踏入更高階的領域。",
    "volume": "在 70 分以上，訓練痕跡開始顯現，常會被問「你有在健身喔？」——這是悉心鍛鍊的成果。外型已明顯跟沒有訓練的人不同；雖然還沒到雜誌封面那麼精緻，但方向正確，持續累積，進步到 80 分、成為高階玩家絕對指日可待。"
  },
  "80": {
    "populationClass": "高階玩家",
    "overall": "你已經是肉體打造的高階玩家了！這個分數獲取不易——一般基因肯定付出大量努力，就算基因優秀也無法輕鬆拿到 80 以上。在這個區間你常常是群眾中最強、最顯眼的；別人在玩樂時你仍訓練不輟，必須給你一個 respect！90 分以上是凡人頂尖，很多運動愛好者把 80 設為最終目標——你已經漂亮達標了！",
    "neuro": "你把「訓練」的優先權排在很多事情前面，光去健身房擺樣子根本達不到目前程度。80 分以上是高階玩家的標誌：在健身房被歸類為高手，在專項競技中也是優秀表現。同時，80 分也是許多運動愛好者的終極目標——你已經漂亮完成了！",
    "volume": "所謂高階玩家，就是現在的你。到了這個程度你已習慣獨自訓練，畢竟願意花這麼多心思的人相對稀少。80 分以上的外型在人群中已是亮點，訓練痕跡清晰可見。若沒有出類拔萃的基因，你就是靠努力與堅持走到這一步；90 分以上是凡人頂尖殿堂，嘗試繼續向前吧！"
  },
  "90": {
    "populationClass": "凡人頂尖",
    "overall": "除非你是基因樂透得主，不然這個分數已是凡人頂尖。走到這一步的你不需要多餘嘉許——你早就不在乎這些。你專注挑戰自我、克服難關才得到這個成果。再往上進入凡體覺醒，投入與回報已不成正比，甚至需要更優選的基因；但即便止步於此，你也已經足夠優秀！",
    "neuro": "若基因屬於常態水準，這成就說明你已把身體開發到天賦極限；這樣的運動表現應用在各專項都已過分充裕，常常是群體中的精英。要再往上，單靠努力不夠，還需要相對應的天賦——但不要灰心，你的努力與表現已是萬里挑一。若你覺得到達這裡並不困難，那凡人頂尖只是你的起點！",
    "volume": "無論基因如何，能到凡人頂尖離不開嚴格紀律與犧牲；你放棄平庸娛樂與社交，把時間投入打造身體。你比其他人傑出的，不只是肉體差距，更是意志力超越。要再往上需要更稀有的天賦，但不論能不能繼續進步，你在人群中已常常是外型最頂尖之一，無法被忽視。"
  },
  "100": {
    "populationClass": "凡體覺醒",
    "overall": "跨越 100 分臨界點，你已進入凡體覺醒——這已不是常人輕易能達到的範疇。需要出眾的天賦，再配合不懈訓練與付出，才能獲得如此評分；有這樣身體能力，應用在專項運動中通常會有極為傑出的表現。我相信你已是相當專業的運動員，無須再給多餘建議，繼續朝自己目標邁進就對了！",
    "neuro": "跨越 100 分意味著你正式踏入凡體覺醒：力量輸出超越多數玩家，在任何健身房或常規運動場上都被歸類為「強者」。對專項競技運動員來說，這個等級已足夠在場上摧枯拉朽；對力量運動員來說，則是打下堅實地基、開始嶄露頭角。這裡已經是凡人禁區之上的覺醒帶！",
    "volume": "能將體態精緻度、重裝肉量或心肺容積推進到 100 分以上，說明你在紀律之餘更擁有讓人嫉妒的天賦。你對身體的掌控已超越單純健康與強壯；在人群中，訓練痕跡與強悍氣場清晰可見，甚至能對周遭產生降維般的視覺壓迫——你已站上凡體覺醒。"
  },
  "110": {
    "populationClass": "超凡入聖",
    "overall": "在這個評分的成員，幾乎都已超凡入聖——是百萬裡挑一、擁有超凡肉體強度的頂級玩家。接受這份稀有座標帶來的重量吧：你不再只是凡人頂尖，而是踏入了更高一階的神格區間。",
    "neuro": "到了超凡入聖，單靠盲目努力與常規訓練已不可能觸及；你正在展現萬中選一的神經募集天賦。力量輸出已達頂尖專項競技與精英力量運動員的水平——基因優勢加上後天苦練，再配合熟練專項技術，將會是賽場上的終極魔王！",
    "volume": "極致功能化的肉體，就是你現在擁有的。在超凡入聖這個區間，投入的時間與紀律已化為無可摧毀的生物資產。最大攝氧功率可達頂尖職業足球、格鬥與籃球運動員的層次；厚實肌肉與拉絲體態比肩一線動作明星與健身偶像。你比其他人傑出的，不只是圍度或速度，更是將孤獨訓練刻進骨血的意志。"
  },
  "120": {
    "populationClass": "歷史級別",
    "overall": "獲得這個評分的你，已站上歷史級別——人類運動史上的佼佼者。頂級綜合肉體強度，全世界只有少數玩家可以與你匹敵。",
    "neuro": "獲得這個分數時，你已在用純粹力量輸出撕裂統計學鐘形曲線，屬於歷史級別的力量區間。在常人眼裡，你的力量與爆發功率已完全無法理解。這說明你擁有頂級天賦，並付出極致努力與巨大犧牲。普通訓練計劃早已無法滿足你；穩紮穩打，你正在向著不朽邁進！",
    "volume": "你的外型與身體機能在現實生活裡已是無法忽視的絕對亮點。這個得分代表你早已放棄平庸社交與娛樂，把生命刻度投入打造身體。肌肉圍度、體脂精緻度或有氧極限功率，已具備歷史級別的含金量——在這個時代絕對可以留下濃墨重彩的一筆。"
  },
  "130": {
    "populationClass": "統計神話",
    "overall": "綜合評分能到這個程度的玩家，已踏入統計神話——地球 Online 伺服器排名前段班的奇蹟造物。我們只能讚嘆這項神話般的成就，這副軀殼是難以複製的奇蹟。",
    "neuro": "你的神經募集與力量表現已是極為優秀的力量運動員水平；頂尖大力士、健力與奧運舉重奪牌選手會在這個統計神話區間出現。光聽到成績就足以讓一般人頭皮發麻。對手已經非常稀少，很多時候只有你自己的紀錄跟你作對。繼續燃燒快肌纖維，你正在親手書寫天梯神話！",
    "volume": "無論基因如何，能走到統計神話的人，在精神意志上都是近乎瘋狂的苦行僧。你對身體的雕琢已是另一個次元；聽到那不可思議的肌肉量、體脂或最大攝氧量，就能聯想到極致紀律、犧牲與天選基因。在人群中，你是難以被複製的標竿，值得被眾人傳頌。"
  },
  "140": {
    "populationClass": "怪物領域",
    "overall": "目前資料庫還沒有這個評分的玩家穩定出現——巨大肌肉量與巨大攝氧量是兩相衝突的生理限制；如果真有如此怪物領域的玩家出現，請讓我們將資料載入主機，永久留存。",
    "neuro": "你已經來到不可思議的怪物領域。拿到 140 以上的高分，意味著神經募集效率與瞬間功率輸出在常人眼裡已是「怪物現象」。普通重量在你面前形同虛設；每次訓練舉起的重量、奔跑速度與起跳高度令人瞠目結舌。你已踩進怪物領域，傲視凡塵，是少數有機會追求「地表最強」稱號的人類！",
    "volume": "這副肉體早已超越「完美體態」的次元，進化成純粹的怪物圖騰。在怪物領域，你投入的時間與近乎瘋狂的紀律近乎詛咒。鏡子裡看到的，是由極致犧牲與怪物級基因複合產出的奇蹟造物。詫異、羨慕、驚恐、崇拜的眼神會從四面八方投射而來——因為你就是「怪物」！"
  },
  "150": {
    "populationClass": "地表最強",
    "overall": "目前資料庫還沒有這個評分的玩家穩定出現——巨大肌肉量與巨大攝氧量是兩相衝突的生理限制；如果真有地表最強級的玩家出現，請讓我們將資料載入主機，永久留存。",
    "neuro": "這裡是碳基肉身的至高穹頂，地表最強稱號被你收入囊中。拿到 150 分以上的頂峰評分，意味著絕對力量輸出已可與人類體育史上的至高傳奇正面對抗；「最強」不再是形容詞，而是事實。凡人窮極一生仰望的天花板，就是你。你的表現是星球的資產。",
    "volume": "這不是單靠紀律就能堆疊出來的肉體——這是可匹敵世界紀錄、造物主最完美的作品之一。你的狀態擊敗了數十億人，直接拿下「地表最強」的無上稱號。當你達到這個成就，歷史就已將你銘記；享受全地球上只屬於你的無上尊榮吧！你，就是地表最強的肉體！"
  }
};

export const DYNO_INTEL_HUMAN_PRAISE_BY_DECADE_EN = {
  "0": {
    "populationClass": "Infant Phase Tier",
    "overall": "In physical training you are in the Infant Phase Tier — it sounds fragile, but it means enormous room to grow. Find an experienced partner to keep you safe; once structured work begins you will progress fast. Grow up quick!",
    "neuro": "In the Infant Phase Tier, progress usually comes fast — master neural recruitment, drill the movements, and you climb quickly. You are not weak; you have not learned how to fire yet. A solid partner or coach can lift your score with visible gains.",
    "volume": "Your body is the sum of past habits — this score mirrors how you have been living. Small changes can rocket you past 40 into the Exploration Phase Tier. Find an experienced partner or coach to build basic training and nutrition structure; you will get stronger and healthier fast."
  },
  "40": {
    "populationClass": "Exploration Phase Tier",
    "overall": "You are in the Exploration Phase Tier: get to know your body, drill movement quality, start pairing food with training, and explore how both reshape you. Train smart and breaking 50 into the Novice Phase Tier is inevitable. The journey just started — explore with fire.",
    "neuro": "The Exploration Phase Tier is where most people begin — you started later, not forever stuck here. Heavy learning and reps are mandatory now. An experienced partner helps you build a safe movement base so you progress fast without stupid injuries.",
    "volume": "You know you are just starting, so do not obsess over this score — results need time to settle. Build new eating habits and time blocks, fuel properly, and invest hours in training. This is a marathon, not a sprint. Stay steady and 50 is absolutely reachable."
  },
  "50": {
    "populationClass": "Novice Phase Tier",
    "overall": "Above 50 you enter the Novice Phase Tier — the on-ramp of healthy norms. Compared with higher operators you may feel like a rookie village, but for daily life this output is already enough. Train right and effort pays back hard — 60 and the General Health Baseline Tier are right around the corner.",
    "neuro": "The Novice Phase Tier is where most gym lovers live — you are standing up on the line. Do not dismiss this score: you are already stronger than most beginners with real bar control and movement skill. Keep going — plenty of room above.",
    "volume": "No obvious physique change yet? Totally normal — skyscrapers start on flat ground. You just poured the foundation. This is the quit zone because change feels half-there. Hold the line — 60+ is guaranteed if you do not stop here."
  },
  "60": {
    "populationClass": "General Health Baseline Tier",
    "overall": "You have reached the General Health Baseline Tier — among training enthusiasts you are already in the consistent cohort. Most untrained or inconsistent people never touch this score. Breaking 70 into the Advanced Trainee Tier takes time and steady work; for average genetics it is a serious climb.",
    "neuro": "At the General Health Baseline Tier you have clearly separated from beginners. Casual lifters rarely hold 60 unless genetics carry them. You train on schedule, watch food, and feel yourself get stronger — effort returns. 70 is not fantasy; it is the paycheck for people who show up.",
    "volume": "Muscles rising, waist shrinking — quiet pride whispers you are doing well. Others may not notice, but you feel the shift. Skills are compounding — keep marching toward 70 and Advanced Trainee Tier."
  },
  "70": {
    "populationClass": "Advanced Trainee Tier",
    "overall": "This score belongs to the Advanced Trainee Tier — consistent work, diet control, and injury avoidance got you here. Respect. In a commercial gym you are probably a standout and people can see the training on you. The next jump into Advanced Operator Tier costs more time and sharper skill — ready?",
    "neuro": "At 70+ you sit in the Advanced Trainee Tier. Most people need serious years to get here. Watch the trap: rapid gains make people rush and get hurt. Stay patient. Your output already supports competitive sport with solid skill — you are in advanced territory.",
    "volume": "Past 70, people start asking if you lift — that is earned. You look different from untrained crowds even if you are not magazine-cover yet. Direction is right — stack months and 80+ Advanced Operator Tier is on the clock."
  },
  "80": {
    "populationClass": "Advanced Operator Tier",
    "overall": "You are an Advanced Operator Tier physique builder now. This score is hard — average genetics means brutal work, and even great genetics cannot coast past 80. You are often the strongest, most visible person in the room. Ninety-plus is Peak Mortal Tier; many lifters treat 80 as the finish line and you nailed it.",
    "neuro": "You ranked training above a lot of life — gym selfies do not get you here. Eighty-plus marks Advanced Operator Tier: labeled advanced in the gym and strong among competitive athletes. Eighty is many people's final boss — you cleared it clean.",
    "volume": "Advanced Operator Tier means you right now. You are used to training alone because few people invest this much. Eighty-plus physique is a spotlight with clear training marks. Without lottery genes you earned this with pure grind — Peak Mortal Tier waits above if you want more."
  },
  "90": {
    "populationClass": "Peak Mortal Tier",
    "overall": "Unless you won the genetic lottery, this score is Peak Mortal Tier. You do not need extra praise — you stopped caring about that long ago. Further gains into Mortal Awakening Tier cost more than they return and may need rarer genetics, but stopping here is already elite.",
    "neuro": "With normal genetics Peak Mortal Tier means you maxed your talent with insane work — your output is more than enough in any sport and often elite in the room. More progress needs genes, not just grind. If this felt easy, Peak Mortal is just your warmup.",
    "volume": "Whatever the genes, Peak Mortal Tier demands discipline and sacrifice — you traded average fun for the body. Going higher needs rarer talent, but in any crowd you are already among the most imposing physiques — impossible to ignore."
  },
  "100": {
    "populationClass": "Mortal Awakening Tier",
    "overall": "Crossing 100 points means Mortal Awakening Tier — no longer ordinary-human territory. Outstanding genetics plus relentless training and sacrifice earn this score; with this physiology, specialty sports usually see extraordinary output. Keep marching toward your own target.",
    "neuro": "Crossing 100 means you have entered Mortal Awakening Tier. In this band your force output leaves most lifters behind — in any gym you are already classified as a predator. For court and combat athletes this tier can dominate; for strength athletes it is the foundation to break through. This is forbidden ground above the mortal peak.",
    "volume": "Pushing physique refinement, loaded muscle, or cardio capacity past 100 means discipline plus enviable genetics. Your body control has moved beyond mere health — in any crowd your training presence is unmistakable. You stand in Mortal Awakening Tier."
  },
  "110": {
    "populationClass": "Ascended Demigod Tier",
    "overall": "Members at this score have almost all Ascended Demigod Tier — one-in-a-million physiques with otherworldly output. Accept the weight of this rare coordinate: you are no longer Peak Mortal alone; you have stepped into a higher sanctum.",
    "neuro": "At Ascended Demigod Tier, blind effort and conventional programming cannot get you here — you display one-in-ten-thousand neural recruitment. Your force output matches elite combat athletes and top strength competitors. Genetic advantage plus brutal training plus sharp skill makes you the final boss on the field.",
    "volume": "A maximally functional physique is what you carry in Ascended Demigod Tier. Your time and discipline have become indestructible biological capital. VO2 ceilings reach terrifying pro tiers; thick muscle and shredded lines rival action icons. You beat others not only on size or speed — you carved lonely training into your bones."
  },
  "120": {
    "populationClass": "Historical Elite Tier",
    "overall": "At this score you stand in Historical Elite Tier — among the greatest physical specimens in athletic history. Top-tier combined strength — only a handful on Earth can stand beside you.",
    "neuro": "At Historical Elite Tier you are tearing through the bell curve with raw force — top-tier strength-athlete territory. To ordinary eyes your power and burst are incomprehensible. Generic programs cannot feed you anymore. Stay steady — you are marching toward myth.",
    "volume": "Your look and physical function are an absolute spotlight in real life. This Historical Elite Tier score means you abandoned mediocre social life and poured every hour into building your body. Your metrics carry historical weight — you could leave a permanent mark on the record books."
  },
  "130": {
    "populationClass": "Statistical Myth Tier",
    "overall": "Players who reach this combined score have entered Statistical Myth Tier — top-band miracles on the Earth Online server. We can only salute this mythic achievement — this chassis is an unreplicable miracle.",
    "neuro": "Your neural recruitment and strength output sit at elite strength-athlete levels inside Statistical Myth Tier — top strongmen, powerlifters, and Olympic medalists appear here. Opponents are scarce — often only your own records stand in your way. Keep burning fast-twitch fibers — you are writing ladder mythology by hand.",
    "volume": "Whatever the genetics, anyone who reaches Statistical Myth Tier is a near-mad ascetic in willpower. Your body sculpting is another dimension — impossible metrics instantly evoke extreme discipline, sacrifice, and lottery-tier genes. In any crowd you are an unreplicable benchmark."
  },
  "140": {
    "populationClass": "Monster Domain Tier",
    "overall": "No player in the database has stably posted this score yet — massive muscle mass and massive aerobic capacity are conflicting physiological limits; if such a Monster Domain Tier athlete appears, load the data into the host and preserve it forever.",
    "neuro": "You have stepped into the Monster Domain Tier. Scoring above 140 means your neural efficiency and instant power output are a monster phenomenon to normal eyes. Ordinary loads are props; the weights you move shock witnesses. You have entered monster territory — one of the few humans who can chase Apex of the Earth.",
    "volume": "This physique has transcended perfect aesthetics into a pure monster totem. In Monster Domain Tier your invested time and near-cursed discipline compound. What you see in the mirror is a miracle forged from extreme sacrifice and monster-tier genes. Stares follow you from every direction — because you are the monster."
  },
  "150": {
    "populationClass": "Apex of the Earth Tier",
    "overall": "No player in the database has stably posted this score yet — massive muscle mass and massive aerobic capacity are conflicting physiological limits; if an Apex of the Earth Tier athlete appears, load the data into the host and preserve it forever.",
    "neuro": "Here is the supreme dome of carbon-based flesh — Apex of the Earth Tier is yours. Scoring above 150 means your absolute force output can stand toe-to-toe with the greatest legends in sports history; strongest is no longer an adjective but a fact. The ceiling mortals spend lifetimes staring at is you.",
    "volume": "This is not a physique stacked by discipline alone — it is world-record-caliber craftsmanship. Your state defeated billions and claimed the Apex of the Earth crown. History has already engraved you — enjoy the supreme honor that belongs only to you on this planet. You are the strongest physique on Earth."
  }
};
