/**
 * AUTO-GENERATED by scripts/sync-dyno-intel-human-praise.mjs — do not edit by hand.
 * Sources:
 * - src/i18n/locales/zh-Hant/common/dynoIntel.json
 * - src/i18n/locales/en/common/dynoIntel.json
 */
export const DYNO_INTEL_PR_PERCENTILE_FALLBACK_ZH = "【全人類官方 PR 值對照資料正在熱烈搜集中】\n\n當資料足夠，會在更新後解鎖；誠摯邀請你幫忙介紹新玩家，一同加速解鎖這座全球肉體極限座標！";

export const DYNO_INTEL_PR_PERCENTILE_FALLBACK_EN = "【Global Peer PR Percentile Data Is Actively Being Gathered】\nWhen sufficient data is accumulated, this feature will unlock via a backend sync. We sincerely invite you to recruit new players to accelerate the calibration of this ultimate coordinate of human physical limits!";

export const DYNO_INTEL_HALL_OF_FAME_SENTENCE_ZH = "在名人堂聖殿中，你正與 {{names}} 站在同一個王座座標。";

export const DYNO_INTEL_HALL_OF_FAME_SENTENCE_EN = "In the Hall of Fame sanctum, you share the same throne coordinate as {{names}}.";

export const DYNO_INTEL_HALL_OF_FAME_LEGAL_SHIELD_ZH = "本系統所收錄之各界名將、藝人運動表現數據，均為其生涯巔峰狀態，源自全球網路公開史料與賽事紀實。部分未公開之空白維度，均由 Dyno Intel 運動科學研究中心依據跨領域生理常模、肌纖維募集比例與物理特質進行高精度推算。本矩陣非臨床與官方賽事認證，數據並非 100% 絕對精準，僅供天梯對帳與娛樂參考。";

export const DYNO_INTEL_HALL_OF_FAME_LEGAL_SHIELD_EN = "All athletic performance metrics of world-class athletes and celebrities stored in this matrix represent their career-peak states, compiled from verified global public archives and official event chronicles. Any unpublished or missing dimensions are calculated via high-precision predictive models by the Dyno Intel Sports Science Research Center, based on cross-disciplinary physiological norms, muscle fiber recruitment ratios, and biomechanical traits. This matrix is not a clinical or sanctioned sporting certification. Data is not 100% absolute and is provided solely for leaderboard simulation, cross-era benchmarking, and entertainment purposes.";

export const DYNO_INTEL_HALL_OF_FAME_BLOCKED_REPLY_ZH = "在 Dyno Intel 的萬神殿深處，該分數帶已正式跨入凡人頂尖的神格區間。你目前的綜合實力尚未解鎖該重力場。拼盡全力訓練吧！當你將功能推向臨界點時，天梯大腦會在你的專屬報告中，為你開啟與該階層歷史傳奇的正面對帳通道！";

export const DYNO_INTEL_HALL_OF_FAME_BLOCKED_REPLY_EN = "In the deepest sanctum of the Dyno Intel Pantheon, this tier has officially crossed into the echelon of elite genetic outliers and peak human godhood. Your current aggregate physical capacity has not yet unlocked this gravitational field. Train harder, leave everything on the gym floor, and return with new numbers. When you push your metrics to the absolute threshold, the Core Mind will unlock the gateway for a direct, cross-era benchmarking session with the legends of this tier in your exclusive briefing.";

export const DYNO_INTEL_HUMAN_PRAISE_BY_DECADE = {
  "0": {
    "populationClass": "生理低谷／亟需啟動評測頁調校",
    "overall": "在身體鍛鍊的世界裡，你目前處於嬰兒階段；雖然聽起來很弱小，但意味著你有巨大的成長空間。建議找經驗豐富的訓練夥伴協助你，確保一切安全無虞；開始系統化鍛鍊後，你將會感受到飛速地進步，快速長大吧！",
    "neuro": "在這個階段，通常會非常快速的進步，只要掌握神經募集的方法，將訓練動作多加熟練，馬上就能往上晉升；換句話說，你不是沒有力氣，只是還沒學會如何發力。衷心建議找個有經驗的訓練夥伴或是專業教練引導，你的評分就能迅速提升，立刻獲得顯著的進步。",
    "volume": "身體是過去生活習慣的累積，現在這個得分，就是過往生活型態的呈現。只要你願意做出稍微的改變，你的分數就會飛也似地成長，馬上突破 40 分。衷心建議找個有經驗的訓練夥伴或是專業教練，引導你建立初步的訓練與飲食架構，你就能迅速提升評分，變得更有力氣、更健康。"
  },
  "40": {
    "populationClass": "擁有巨大進步潛力新手期",
    "overall": "在這個階段，要好好認識自己的身體，認真地熟練訓練動作，開始注重飲食的搭配，並且去探索訓練和飲食，如何影響自己的身體？只要訓練搭配得當，往50分以上邁進是必然的。這趟旅程才剛剛開始，充滿熱情的探索吧！",
    "neuro": "這裡是大多數人的起始之地，你只是開始得比較晚，不會永遠停在這裡，甚至很快可以往上晉升。在這個階段，大量的學習跟實作是必要的，衷心建議找個有經驗的訓練夥伴，協助你建構初步的動作架構，這樣既可以安全且快速地進步，又能有效避免傷病。",
    "volume": "你也知道自己剛剛開始，所以不要太在意這個階段的分數，訓練成果是需要時間沉澱的。在這個階段，要建立新的飲食習慣與時間分配，注重營養攝取，並投入時間訓練。要獲得好的體態，心態必須非常正確，這場計劃不是衝刺短跑，而是一場馬拉松；持之以恆， 50 分絕對可以達成。"
  },
  "50": {
    "populationClass": "健康常模大眾平均水平",
    "overall": "評分來到50以上，你已經位於大眾平均水平了。雖然跟大神們比較起來，會覺得自己還在新手村，但其實目前的運動表現，套用在日常生活裡，已經很足夠。只要方式正確，在目前階段，投入的努力跟獲得的回報，是高度成正比，進步到60分指日可待！",
    "neuro": "這個階段是最多健身愛好者的所在地，說明你已經漸漸站穩腳步，來到大眾的平均水平了。不要覺得在這個分數沒有什麼了不起，你已經比大部分菜鳥玩家有力氣，對於重量掌控與技術動作，已有一定的純熟度。看到身邊或是網路上很多大神展現驚人的運動表現，或許會覺得自己的表現微不足道，但其實目前的力量，對日常生活和健康已大有幫助，持之以恆，往上還有許多空間可以進步。",
    "volume": "現在看不出來身材有明顯的改變，非常正常，萬丈高樓平地起，目前看過去雖然是平地，但要記得，你才剛剛打好地基，正蓄勢待發。在這個階段最容易讓人放棄，因為好像有點改變卻又不明顯；這時候最重要的是堅定信念，一定能進步到 60 分以上，千萬不要在此停下腳步。"
  },
  "60": {
    "populationClass": "擁有規律運動習慣族群（略優於大眾水平）",
    "overall": "你的表現在運動愛好者之中，已經是優秀的族群了。大多數沒訓練、訓練頻率不夠的玩家，是拿不到這個評分的，這也證明了你的投入有所回報；如果你很輕鬆就獲得這個分數，那你的基因相當優秀，值得好好開發。想進步到70分以上的，需要時間的累積，持續且沉穩的努力，對一般基因的常人來說，70分是富含挑戰性的目標。",
    "neuro": "你能走到這一步，各項表現已經明顯跟新手拉開了差距。沒有訓練或是偶爾訓練的玩家，除非擁有優秀的基因，不然根本無法拿到 60 分以上的評分。你已經開始規律地訓練、開始注意飲食，也漸漸發現自己越變越強，付出努力就會獲得回報，說的就是這麼一回事。期待你可以更上一層樓， 70 分並非遙不可及，這是努力者都能獲得的報酬。",
    "volume": "看著漸漸隆起的肌肉，或是漸漸消瘦的腰圍，成就感在心底偷偷地說：「是的，你真的很不錯！」也許別人不一定察覺，但你一定有察覺自己的身體漸漸在改變。你可能已經訓練了一小陣子，幾個當初說要一起鍛鍊的夥伴可能已經放棄了，但付出的努力不會背叛，你的身體正在顯著改善。在這個階段你已經逐漸熟練，投入的心力都會顯著轉換為成果，期待你繼續往 70 分邁進。"
  },
  "70": {
    "populationClass": "商業健身房傑出族群",
    "overall": "這個評分，是屬於進階訓練者的，規律訓練、飲食控制，避免傷病，才能走到這一步，必須給你比個讚。你在商業健身房裡，高機率是最優秀的玩家之一，訓練痕跡也很容易被別人察覺。目前的運動表現，在專項運動中已經相當有競爭力了。要再往上進步，需要投入的時間成本將會顯著提升，相關的訓練技術也要更精進，需要你設定更高的目標，準備好了嗎？",
    "neuro": "獲得這個分數時，你的運動表現已經屬於健身房裡傑出的族群。絕大多數人都要悉心鍛鍊，才能獲得 70 分以上的評分，能有如此表現絕非一蹴可及。要特別注意的是，在這個階段的許多玩家，因為已經品嚐到努力帶來的顯著進步，會開始急於求成；一不小心，傷病就會找上門來。穩紮穩打，方能持續進步。你現在的運動表現應用在各專項競技項目上已經十分足夠，配合熟練的專項技術，已經踏入高手領域。",
    "volume": "在 70 分以上時，訓練痕跡開始顯現，常常會被身邊的人詢問：「你有在健身喔？」這完全是你悉心鍛鍊成果的展現，你可以心安理得地享受這份成就感。你的外型已經明顯跟沒有訓練的玩家有所不同，雖然還沒到雜誌封面、健身網紅那麼精緻顯眼，但你已經掌握了正確方向，只要持續累積，進步到 80 分以上絕對是指日可待。"
  },
  "80": {
    "populationClass": "業餘運動員中優秀表現",
    "overall": "你已經是肉體打造的高級玩家了！這個分數獲取不易，你的基因如果屬於一般水準，那肯定付出了大量的努力，就算基因相當優秀，也無法輕輕鬆鬆拿到80以上的評分。在這個區間，你肯定已經察覺，你常常是群眾中最強、最顯眼的，不只在生理上忍受訓練的辛苦和汗水，心理上也要忍受相對的犧牲，別人在玩、在享樂時，你依然訓練不輟，必須要給你一個respect！90分以上是凡人頂尖族群，想爬上去需要投入更大量的時間，因此很多運動愛好者都把80分這個區間設定為最終的目標，你已經漂亮的達標了！",
    "neuro": "你把「訓練」這個任務的優先權排在很多事情前面，光去健身房拍拍照、擺擺樣子，根本達不到目前的程度，相當值得嘉許。 80 分以上是群眾中的佼佼者，在健身房中已經被歸類為高手，在專項競技運動員中也是優秀的表現，許多優秀的籃球員、格鬥運動員或健美運動員的力量表現，就在這個範圍。同時， 80 分也是許多運動愛好者的終極目標，你已經漂亮地完成了！",
    "volume": "所謂的高階訓練者，就是指現在的你。到了這個程度，你已經習慣獨自訓練了，畢竟願意花這麼多心思在鍛鍊的人已經相對稀少。 80 分以上的外型表現，在人群中已經是一大亮點，訓練痕跡清晰可見。如果沒有出類拔萃的基因，你就是靠著存粹的努力跟堅持走到這一步，而 90 分以上是凡人基因的最高殿堂，嘗試繼續向前吧！"
  },
  "90": {
    "populationClass": "地區型各類賽事常勝軍",
    "overall": "除非你是基因樂透得主，不然這個分數，已經是凡人的頂點了！走到這一步的你，不需要我給予任何嘉許，因為你早就不在乎這些。你非常專注在挑戰自我，克服許多難關，才能得到這個成果。接下來要再往上進步，投入跟付出已經不成正比了，甚至需要優選基因的幫助，但即便止步於此，你也已經足夠優秀！如果你覺得達到這個分數並不困難，那你擁有天選基因，看好你突破凡人極限！",
    "neuro": "如果你的基因是屬於常態水準，這成就說明你已經付出極致的努力，把身體開發到天賦的極限了；這樣的運動表現，應用在各專項運動上都已經過分充裕，甚至常常是群體中的精英。要再往上進步，單靠努力是不夠的，必須要有相對應的天賦，但不要覺得灰心，你的努力程度跟展現出來的運動表現，已經是萬里挑一。但如果你覺得到達這裡並不困難，那說明你擁有超乎常人的天賦，繼續衝刺吧！凡人的天花板只是你的起點！",
    "volume": "無論基因如何，能夠到這個程度，離不開嚴格的紀律和犧牲；你放棄了平庸的娛樂與社交，把時間都投入在打造自己的身體上。你比其他人傑出的，不只是肉體上的差距，更是意志力上的超越。要再往上，需要萬中選一的基因，但不論能不能繼續進步，你在人群中，已經常常是外型最頂尖之一，無法被忽視。"
  },
  "100": {
    "populationClass": "國家級賽事常勝軍",
    "overall": "跨越 100 分的臨界點，已經不是正常人可以達到的範疇。只有天賦異稟的優選基因，再配合不懈的訓練與付出，才能獲得如此評分；有這樣身體能力，應用在專項運動中，通常都會有極為傑出的表現；我相信你已經是相當專業的運動員了，無須再給你什麼建議，繼續朝自己目標邁進就對了！",
    "neuro": "跨越 100 分的臨界點，意味著你正式加入了非凡基因才能踏入的領域。在這個區間，你的力量輸出超越多數玩家，在任何健身房或常規運動場上，都已經被歸類為「強者」。對於專項競技運動員來說，這個等級的力量已足夠在場上摧枯拉朽；對於力量運動員來說，則是打下堅實的地基，要開始嶄露頭角。你擁有超乎常人的天賦及付出，這裡已經是凡人禁區了！",
    "volume": "能夠將體態的精緻度、重裝肉量或心肺容積推進到 100 分以上，這說明你在紀律之餘，更擁有讓人嫉妒的高級天賦。你對身體的掌控已經超越了單純的健康與強壯，在人群中，你的訓練痕跡與強悍氣場清晰可見，甚至能對周遭產生降維般的視覺壓迫。你的肉體狀態，已經是超越凡人的存在了。"
  },
  "110": {
    "populationClass": "國家級頂尖運動員",
    "overall": "在這個評分的成員，幾乎都是世界級的頂尖運動員，是百萬裡挑一、擁有超凡入聖的肉體強度的頂級玩家，接受凡人們的膜拜吧！",
    "neuro": "到了這個段位，單靠盲目的努力與常規訓練已經不可能觸及，你正在展現萬中選一的神經募集天賦。你的力量輸出，已經達到頂尖專項競技運動員和精英力量運動員的水平，許多格鬥運動員、棒球或籃球運動員的世界冠軍，都在這個區間。基因的優勢，加上後天的苦練，配合上熟練的專項技術，將會是賽場上的終極魔王！",
    "volume": "極致功能化的肉體，就是你現在擁有的。在這個區間，你投入的時間與紀律，已經化為無可摧毀的生物資產。你的最大攝氧量功率，已經到了達到頂尖職業足球員、格鬥運動員跟籃球運動員的恐怖層次；厚實的肌肉跟拉絲的體態，已經比肩一線好萊塢藝人跟健身男模。你比其他人傑出的，不只是肉體上的圍度或速度，更是將孤獨訓練刻進骨血的極致意志力，還有對勝利的渴望。"
  },
  "120": {
    "populationClass": "國際大師級運動員",
    "overall": "獲得這個評分的你，已經是人類運動史上的佼佼者。頂級的綜合肉體強度，全世界只有少數玩家可以與你匹敵。",
    "neuro": "獲得這個分數時，你已經在用純粹的力量輸出撕裂統計學的鐘形曲線，屬於頂尖力量運動員的區間。在常人眼裡，你的力量與爆發功率已經完全無法理解。這說明你擁有頂級的天賦，並且付出了極致努力，忍受巨大的犧牲。普通的訓練計劃早已無法滿足你，你的一舉一動都在刷新健身房的歷史紀錄。穩紮穩打，你正在向著不朽的神話邁進！",
    "volume": "你的外型與身體機能，在現實生活裡已經是一道無法被忽視的絕對亮點。這個得分代表你早已放棄了平庸的社交與娛樂，把生命所有的刻度都投入在打造自己的身體上。你的肌肉圍度、體脂精緻度或有氧極限功率，已經具備了歷史級別的含金量，在這個互聯網的時代，絕對可以在歷史上留下濃墨重彩的一筆。"
  },
  "130": {
    "populationClass": "世界頂尖運動員層級",
    "overall": "綜合評分能到這個程度的玩家，已經是地球Online伺服器排名前十的玩家了。我們只能讚嘆這項神話般的成就，這副軀殼是難以複製的奇蹟。",
    "neuro": "你的神經募集與力量表現，已經是極為優秀的力量運動員水平，頂尖大力士、健力運動員、奧運舉重奪牌選手，會在這個區間出現；光聽到你運動表現的成績，就足以讓一般人頭皮發麻。你的對手已經非常稀少了，很多時候都只有你自己的紀錄跟你作對。繼續燃燒你的快肌纖維，你正在親手書寫屬於你自己的天梯神話！",
    "volume": "無論基因如何，能走到這一步的人，在精神意志上都是近乎瘋狂的苦行僧。你對身體的雕琢已是另外一個次元，聽到那不可思議的肌肉量、體脂肪率或是最大攝氧量，就能聯想到極致紀律、犧牲與天選基因；也必須如此，才能複合產出如此的奇蹟造物。在人群中，你是難以被複製的標竿，你那不可思議的狀態，值得被眾人傳頌。"
  },
  "140": {
    "populationClass": "極限天賦神殿層級",
    "overall": "目前資料庫還沒有這個評分的玩家出現，巨大的肌肉量和巨大的攝氧量是兩相衝突的生理限制；如果真有如此怪物般的玩家出現，請讓我們將資料載入主機，永久留存。",
    "neuro": "你已經來到不可思議的「怪物領域」了。拿到 140 以上的高分，意味著你的神經募集效率與瞬間功率輸出，在常人眼裡已經是「怪物現象」，讓人無比好奇你是怎麼做到的？普通的重量在你面前早已形同虛設，每次訓練時你舉起的重量、奔跑的速度跟起跳的高度，令人瞠目結舌。在任何健身房或競技場上，你的一舉一動都令人生畏，在你的天賦面前，絕大多數的對手只能被降維打擊。你已經踩進了怪物領域，傲視凡塵，是少數有機會追求「地表最強」稱號的人類！",
    "volume": "這副肉體早已超越了「完美體態」的次元，進化成了一種純粹的怪物圖騰。在這個區間，你投入的時間，與近乎瘋狂的紀律，近乎詛咒。你在鏡子裡看到的，是由極致犧牲與怪物級基因，複合產出的奇蹟造物。你的拉絲體態、巨大肌肉圍度或最大攝氧量，是一具被推向極限改造的非人肉體。在人群中，詫異、羨慕、驚恐、崇拜或是好奇的眼神，會從四面八方投射而來，因為你就是「怪物」！"
  },
  "150": {
    "populationClass": "突破生理常模極限",
    "overall": "目前資料庫還沒有這個評分的玩家出現，巨大的肌肉量和巨大的攝氧量是兩相衝突的生理限制；如果真有如此怪物般的玩家出現，請讓我們將資料載入主機，永久留存。",
    "neuro": "這裡，是碳基肉身的至高穹頂，地表最強稱號被你收入囊中。拿到 150分以上的頂峰評分，意味著你的絕對力量輸出，已經可以直接與整部人類體育史上的至高傳奇正面對抗；「最強的力量」，不再是形容詞，而是描述一件事實，在世界上的強者之林中，你絕對是無可爭議的霸主之一，你單憑肉身，就將重力踩在了腳下。凡人窮極一生仰望的天花板，就是你。你的表現是星球的資產。",
    "volume": "這不是單靠紀律就能堆疊出來的肉體，這是可匹敵世界紀錄，造物主最完美的作品。你的狀態擊敗了數十億人，直接拿下了「地表最強」的無上稱號。當你達到這個成就，歷史就已經將你銘記，時間和老化都抹滅不了你的頂尖；人類總追求超越極限，你就是極限的代名詞，注定不可能被遺忘。享受全地球上只屬於你的無上尊榮吧！你，就是地表最強的肉體！"
  }
};

export const DYNO_INTEL_HUMAN_PRAISE_BY_DECADE_EN = {
  "0": {
    "populationClass": "physiological low point needing assessment reset",
    "overall": "In the world of physical training you're still in the infant stage — it sounds fragile, but it means enormous room to grow. Find an experienced training partner to keep you safe; once you start structured work you'll progress fast. Grow up quick!",
    "neuro": "At this stage progress usually comes very fast — master neural recruitment, drill the movements, and you'll climb quickly. You're not weak; you just haven't learned how to fire yet. A solid partner or coach can lift your score fast with visible gains.",
    "volume": "Your body is the sum of past habits — this score mirrors how you've been living. Small changes can make your score rocket past 40. Find an experienced partner or coach to build basic training and nutrition structure; you'll get stronger and healthier fast."
  },
  "40": {
    "populationClass": "high-upside beginner phase",
    "overall": "At this stage get to know your body, drill movement quality, start pairing food with training, and explore how both reshape you. Train smart and breaking 50 is inevitable. The journey just started — explore with fire.",
    "neuro": "This is where most people begin — you started later, not forever stuck here, and you can climb soon. Heavy learning and reps are mandatory now. An experienced partner helps you build a safe movement base — progress fast without stupid injuries.",
    "volume": "You know you're just starting, so don't obsess over this score — results need time to settle. Build new eating habits and time blocks, fuel properly, and invest hours in training. The right mindset matters: this isn't a sprint, it's a marathon. Stay steady and 50 is absolutely reachable."
  },
  "50": {
    "populationClass": "healthy population average",
    "overall": "Above 50 you're at the healthy population average. Compared to elites you may feel like a rookie village, but for daily life this output is already enough. Train right and effort pays back hard at this stage — 60 is right around the corner.",
    "neuro": "This is where most gym lovers live — you're standing on the average line. Don't dismiss this score: you're already stronger than most beginners with real bar control and movement skill. Online gods look insane, but your current strength already helps daily life and health. Keep going — plenty of room above.",
    "volume": "No obvious physique change yet? Totally normal — skyscrapers start on flat ground. You just poured the foundation and you're loading. This is the quit zone because change feels half-there. Hold the line — 60+ is guaranteed if you don't stop here."
  },
  "60": {
    "populationClass": "regular exerciser slightly above average",
    "overall": "Among training enthusiasts you're already in the strong cohort. Most untrained or inconsistent people never touch this score — your investment paid back. If this felt easy, your genetics are legit and worth mining. Breaking 70 takes time and steady work; for average genetics it's a serious climb.",
    "neuro": "You've clearly separated from beginners. Casual lifters rarely crack 60 unless genetics carry them. You're training on schedule, watching food, and feeling yourself get stronger — effort returns, period. 70 isn't fantasy; it's the paycheck for people who show up.",
    "volume": "Muscles rising, waist shrinking — quiet pride whispers you're doing well. Others may not notice, but you feel the shift. Training buddies may have quit; your effort won't betray you. Skills are compounding — keep marching toward 70."
  },
  "70": {
    "populationClass": "standout commercial-gym cohort",
    "overall": "This score belongs to advanced trainees — consistent work, diet control, and injury avoidance got you here. Respect. In a commercial gym you're probably top-tier and people can see the training on you. Your output is already competitive in specialty sports. The next jump costs more time and sharper skill — ready for a higher target?",
    "neuro": "At 70+ you're standout gym floor talent. Most people need serious years to get here — this wasn't luck. Watch the trap: rapid gains make people rush and get hurt. Stay patient. Your output already supports competitive sport with solid skill — you're in advanced territory.",
    "volume": "Past 70, people start asking if you lift — that's earned. You look different from untrained crowds even if you're not magazine-cover yet. Direction is right — stack months and 80+ is on the clock."
  },
  "80": {
    "populationClass": "strong amateur athlete performance",
    "overall": "You're a high-level physique builder now. This score is hard — average genetics means brutal work, and even great genetics can't coast past 80. You're often the strongest, most visible person in the room. You paid in sweat and sacrificed play time while others partied — respect. Ninety-plus is mortal apex; many lifters treat 80 as the finish line and you nailed it.",
    "neuro": "You ranked training above a lot of life — gym selfies don't get you here. Eighty-plus is elite in the crowd, labeled advanced in the gym, and strong among competitive athletes. Plenty of court fighters and physique pros live in this band. Eighty is many people's final boss — you cleared it clean.",
    "volume": "High-level trainee means you right now. You're used to training alone because few people invest this much. Eighty-plus physique is a spotlight with clear training marks. Without lottery genes you earned this with pure grind — ninety-plus is the mortal hall. Keep pushing if you want more."
  },
  "90": {
    "populationClass": "regional multi-event perennial winner",
    "overall": "Unless you won the genetic lottery, this score is the mortal ceiling. You don't need my praise — you stopped caring about that long ago. You chased yourself through hell to get here. Further gains cost more than they return and may need elite genes, but stopping here is already elite. If this felt easy, you're chosen — break the mortal limit.",
    "neuro": "With normal genetics this means you maxed your talent with insane work — your output is more than enough in any sport and often elite in the room. More progress needs genes, not just grind — don't despair, your effort-to-output ratio is one-in-ten-thousand. If this was easy, you're built different — mortal ceiling is just your warmup.",
    "volume": "Whatever the genes, this level demands discipline and sacrifice — you traded average fun and social time for the body. You beat people on flesh and willpower. Going higher needs lottery-tier genetics, but in any crowd you're already among the most imposing physiques — impossible to ignore."
  },
  "100": {
    "populationClass": "national event perennial winner",
    "overall": "Crossing the 100-point threshold is no longer normal-human territory. Only elite genetics plus relentless training and sacrifice earn this score; with this physiology, specialty sports usually see extraordinary output. I believe you're already a serious athlete — no advice needed, keep marching toward your own target.",
    "neuro": "Crossing 100 points means you've entered a realm only extraordinary genetics can touch. In this band your force output leaves most lifters behind — in any gym or conventional field you're already classified as a predator. For court and combat athletes this tier is enough to dominate; for strength athletes it's the foundation to start breaking through. You carry rare talent and rare work — this is mortal forbidden ground.",
    "volume": "Pushing physique refinement, loaded muscle mass, or cardio capacity past 100 points means discipline plus enviable genetics. Your body control has moved beyond mere health and strength — in any crowd your training presence and aura are unmistakable, even imposing. Your physical state has already stepped past ordinary humanity."
  },
  "110": {
    "populationClass": "national elite athlete",
    "overall": "Members at this score are almost all world-class athletes — one-in-a-million physiques with otherworldly output. Accept the worship of mortals.",
    "neuro": "At this tier blind effort and conventional programming can't get you here — you're displaying one-in-ten-thousand neural recruitment. Your force output matches elite combat athletes and top strength competitors; UFC champions, MLB stars, and NBA legends live in this band. Genetic advantage plus brutal training plus sharp skill makes you the final boss on the field.",
    "volume": "A maximally functional physique is what you carry now. In this band your time and discipline have become indestructible biological capital. Your VO2 ceiling reaches terrifying pro-soccer, combat, and basketball tiers; thick muscle and shredded lines rival A-list action stars and fitness icons. You don't just beat others on size or speed — you've carved lonely training into your bones and hunger for victory into your identity."
  },
  "120": {
    "populationClass": "international master athlete",
    "overall": "At this score you are already among the greatest physical specimens in human athletic history. Top-tier combined strength — only a handful on Earth can stand beside you.",
    "neuro": "At this score you're tearing through the bell curve with raw force output — top-tier strength-athlete territory. To ordinary eyes your power and burst are incomprehensible. That means elite talent, extreme sacrifice, and suffering most won't endure. Generic programs can't feed you anymore — every session rewrites gym history. Stay steady — you're marching toward myth.",
    "volume": "Your look and physical function are an absolute spotlight in real life. This score means you abandoned mediocre social life and entertainment and poured every hour into building your body. Your muscle mass, body-fat precision, or aerobic ceiling carry historical weight — in the internet age you could leave a permanent mark on the record books."
  },
  "130": {
    "populationClass": "world-top athlete tier",
    "overall": "Players who reach this combined score are top-ten on the Earth Online server. We can only salute this mythic achievement — this chassis is an unreplicable miracle.",
    "neuro": "Your neural recruitment and strength output sit at elite strength-athlete levels — top strongmen, powerlifters, and Olympic medalists appear here; hearing your numbers alone makes ordinary people shiver. Opponents are scarce — often only your own records stand in your way. Keep burning fast-twitch fibers — you're writing your own ladder mythology by hand.",
    "volume": "Whatever the genetics, anyone who reaches this step is a near-mad ascetic in willpower. Your body sculpting is another dimension — impossible muscle mass, body-fat readings, or max VO2 instantly evoke extreme discipline, sacrifice, and lottery-tier genes; nothing less could forge this miracle. In any crowd you're an unreplicable benchmark — your state deserves to be sung."
  },
  "140": {
    "populationClass": "extreme talent temple tier",
    "overall": "No player in the database has posted this score yet — massive muscle mass and massive aerobic capacity are conflicting physiological limits; if such a monster appears, load the data into the host and preserve it forever.",
    "neuro": "You've stepped into the unbelievable Monster Domain. Scoring above 140 means your neural efficiency and instant power output are a monster phenomenon to normal eyes — everyone wonders how you did it. Ordinary loads are props; the weights you move, speeds you run, and heights you jump shock witnesses. In any gym or arena your presence intimidates — most opponents face dimensional suppression. You've entered monster territory, looking down on mortals — one of the few humans who can chase the title of strongest on Earth.",
    "volume": "This physique has transcended perfect aesthetics into a pure monster totem. In this band your invested time and near-cursed discipline compound. What you see in the mirror is a miracle forged from extreme sacrifice and monster-tier genes. Shredded lines, massive muscle, or max VO2 — a body pushed past human limits. Stares of shock, envy, fear, worship, and curiosity follow you from every direction — because you are the monster."
  },
  "150": {
    "populationClass": "beyond conventional physiological norms",
    "overall": "No player in the database has posted this score yet — massive muscle mass and massive aerobic capacity are conflicting physiological limits; if such a monster appears, load the data into the host and preserve it forever.",
    "neuro": "Here is the supreme dome of carbon-based flesh — the strongest-on-Earth title is yours. Scoring above 150 means your absolute force output can stand toe-to-toe with the greatest legends in all of human sports history; strongest is no longer an adjective but a fact. Among the world's apex predators you are an undisputed sovereign — you stomp gravity with flesh alone. The ceiling mortals spend lifetimes staring at is you. Your output is planetary capital.",
    "volume": "This isn't a physique stacked by discipline alone — it's a world-record-caliber masterpiece of creation. Your state defeated billions and claimed the supreme strongest-on-Earth crown. When you reach this achievement history has already engraved you — time and aging cannot erase your peak; humanity always chases limits and you are the synonym for limit, impossible to forget. Enjoy the supreme honor that belongs only to you on this planet — you are the strongest physique on Earth."
  }
};
